name: demo
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  app_version_update: ^4.0.1
  bloc: ^8.1.2
  bot_toast: ^4.0.4
  cached_network_image: ^3.2.3
  equatable: ^2.0.5
  fast_immutable_collections: ^9.1.5
  flex_color_scheme: ^7.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_easylogger: ^2.3.3
  # flutter_html: ^2.1.2
  # flutter_html: ^2.1.2
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.8.4
  flutter_svg: ^0.23.0+1
  font_awesome_flutter: ^10.5.0
  form_validator: ^2.1.1
  fpdart: ^1.0.0
  gap: ^3.0.1
  go_router: ^10.0.0
  google_fonts: ^5.1.0
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.3.7
  http: ^1.1.0
  image_picker: ^1.0.1
  intl: ^0.18.0
  pinput: ^3.0.0
  timeago: ^3.5.0

dev_dependencies:
  bloc_test: ^9.1.2
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  # very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
